version: 0.2

phases:
  pre_build:
    commands:
      - pip install -r requirements.txt
      - pip install -r test_requirements.txt
  build:
    commands:
      - nosetests
      

artifacts:
  files:
    - xfer-test/
